spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: AppointmentMS
          uri: lb://AppointmentMS
          predicates:
            - Path=/appointment/**
        - id: DoctorMS
          uri: lb://DoctorMS
          predicates:
            - Path=/doctor/**
        - id: PatientMS
          uri: lb://PatientMS
          predicates:
            - Path=/patient/**   